### ISSUE TITLE
The demo is not working in the browser

### ISSUE THREAD

**Issue by frankrousseau** [arch-inc/fabricjs-psbrush#11]
Hello there,

Thank you a lot for this plugin. It's something we are looking for for a while. I will see if I can contribute in any way.

The sad thing is that it seems to not work on a desktop computer. Is there any way we can help to add the compatibility with desktop browsers?

**Comment by arcatdmz** [comment]
Hi @frankrousseau, thank you for your interest in our project!

I've just checked the demo website with my Wacom One device on the latest release build of Microsoft Edge, which worked properly.

![image](https://user-images.githubusercontent.com/627194/104674012-3422c600-5726-11eb-81d2-ca15369803a9.png)

Our implementation uses either one of `TouchEvent.touches[0].force` or `PointerEvent.pressure` values, so please confirm that your web browser supports these APIs.

https://github.com/arch-inc/fabricjs-psbrush/blob/3a665a20d597a5156d9b2790610bc0af59ef34ab/lib/utils.ts#L28-L39

By the way, I've noticed you're working on helping Animation Studios. We ([Arch Research](https://research.archinc.jp/en/)) share the goal, though we are based in Japan and currently focus on Japanese anime production workflow. Glad to get to know fellows abroad!

**Comment by frankrousseau** [comment]
I use Firefox and Chrome. Can it work with the mouse?
My friend who tried it with a pencil use Google Chrome.

**Comment by arcatdmz** [comment]
It should also work on Firefox and Chrome.

Adding support for mouse is another thing, because it usually doesn't have any pressure information (just 0 [up] or 1 [down]) and we need to somehow simulate the pressure.
For instance, we could probably utilize stroke speed for the simulation.

Oh, and thank you for the information. The list itself is super useful.

We also had a similar article in our booklet called "[Anime Technology](https://research.archinc.jp/en/anitech/)" but it's written in Japanese. This video shows something relevant, if you're interested in how Japanese anime is made:
https://www.youtube.com/watch?v=2DSnKa--aMM

**Comment by arcatdmz** [comment]
I believe this issue is resolved with the introduction of [PressureManager](https://github.com/arch-inc/fabricjs-psbrush/blob/5ef7197e75ad2bcede181be45df3642fa7118084/lib/PressureManager.ts) and its `fallback` value.

I'm closing this issue, but please feel free to re-open, @frankrousseau.

**Comment by frankrousseau** [comment]
Thank you, I will try to integrate your tool again.
